# Drupal recipe for the news content type.
#
# This recipe installs the news content type and its dependencies.
# It also includes configuration for the content type, fields, and views.
#

name: 'News Content Type'
description: |
  This recipe installs the news content type and its dependencies.
  It also includes configuration for the content type, fields, and views.
type: 'Content type'
install:
  - node
  - field
  - text
  - options
  - datetime
  - file
  - image
  - link
  - views
  - views_ui
  - media
  - media_library
  
config:
  strict:
    - field.storage.node.body
    - field.storage.node.field_description
    - field.storage.node.field_featured_image
    - field.storage.node.field_tags
  import:
    filter: '*'
    node:
      # Only import config which is also imported by the Standard profile.
      - field.storage.node.body
      - system.action.node_delete_action
      - system.action.node_make_sticky_action
      - system.action.node_make_unsticky_action
      - system.action.node_promote_action
      - system.action.node_publish_action
      - system.action.node_save_action
      - system.action.node_unpromote_action
      - system.action.node_unpublish_action
